### ISSUE TITLE
pybalboa.balboa Pipe Broken

### ISSUE THREAD

**Issue by stringy92** [garbled1/balboa_homeassistan#3]
I am using the HACS version, and manually updated manifest.json to reference the update pybalboa to 0.6 and now i am logging the following error every 1second

2020-05-26 11:52:48 ERROR (MainThread) [pybalboa.balboa] Spa socket error: [Errno 32] Broken pipe

**Comment by garbled1** [comment]
Sometimes the wifi box is super flaky.  Mine would freak out sometimes and drop it's IP and renegotiate DHCP.  If I restarted hass it would suddenly be ok, and back to normal.  I fixed that particular problem recently, but I haven't seen the pipe error commonly..

If you restart hass, does the wifi box reconnect and go back to normal, or does it immediately go into broken pipe?  Can you ping the wifi box?  I can throw a fix in for the EPIPE error if it just happens sometimes, but if it's immediate and never works, hrmm.. then maybe I broke something else..

**Comment by garbled1** [comment]
Oh, one more thought, if you updated only the manifest, there was another change in 0.6...it might have broken something..  can you update the integration to master?

**Comment by stringy92** [comment]
Amended to the current updated files, and he issue has now been resolved

**Comment by stringy92** [comment]
Re-opening the issue, as i am unable to amend the temperature, ive had the following error messages

2020-05-26 20:35:18 ERROR (MainThread) [pybalboa.balboa] Spa read failed: 0 bytes read on a total of 2 expected bytes

2020-05-26 20:39:53 ERROR (MainThread) [pybalboa.balboa] Spa stopped responding, requesting panel config.
2020-05-26 20:39:53 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pybalboa/balboa.py", line 790, in check_connection_status
    await self.send_panel_req(0, 1)
  File "/usr/local/lib/python3.7/site-packages/pybalboa/balboa.py", line 252, in send_panel_req
    await self.writer.drain()
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 348, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2020-05-26 20:39:54 ERROR (MainThread) [pybalboa.balboa] Spa socket error: [Errno 32] Broken pipe


It is worth noting these are now being reported every second

**Comment by garbled1** [comment]
OK, let me do some more testing on my end.  Did you update the integration to master as well, or just pybalboa?

**Comment by stringy92** [comment]
Updated to the master and no longer getting the error. Was this made with the intention of a 2 pump spa? I have a 3 pump spa, and find the switching of the pumps to cause an issues. However I am more than happy to help correct this

**Comment by garbled1** [comment]
I own a 2 pump spa, mode 4, which has 2 2-speed pumps.    I did my best to guess at how some of the other setups worked, especially the 1 speed pumps.

In theory the 1 speed pumps should work now, but you are saying they don't?  I absolutely want to fix this though.  Would you mind opening a new issue and maybe detail out what happens when you do various things, maybe we can figure it out together?

As for this issue, I'll do a little more testing and then go push a release, so the two are in sync.

**Comment by stringy92** [comment]
Thanks for the support, ill open a new issue
