### ISSUE TITLE
Error setting up entry Balboa Spa for balboa

### ISSUE THREAD

**Issue by jurrianv** [garbled1/balboa_homeassistan#7]
Hi,

Suddenly I have problems with the Balboa integration for Home Assistant. I use the HA version 0.114.4. I have no Idea how to solve this.

This is the info from the log:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/balboa/__init__.py", line 54, in async_setup_entry
    connected = await spa.connect()
  File "/usr/local/lib/python3.8/site-packages/pybalboa/balboa.py", line 190, in connect
    self.reader, self.writer = await asyncio.open_connection(self.host,
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('_my_balboa_ip_', 4257)

**Comment by jurrianv** [comment]
I fixed it myself. I removed the integration and added it again.
